# Generated by Django 3.2.8 on 2021-10-12 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='identity',
            fields=[
                ('img', models.ImageField(upload_to='images/')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('citizen', models.CharField(max_length=3)),
                ('personal_no', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('birthday_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('birth_place', models.CharField(max_length=35)),
                ('issue_date', models.DateField()),
            ],
        ),
    ]
