# Generated by Django 3.2.8 on 2021-10-12 15:24

from django.db import migrations, models
import piradoba.validators


class Migration(migrations.Migration):

    dependencies = [
        ('piradoba', '0003_identity_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='birth_place',
            field=models.CharField(max_length=20, validators=[piradoba.validators.Capital]),
        ),
        migrations.AlterField(
            model_name='identity',
            name='first_name',
            field=models.CharField(max_length=10, validators=[piradoba.validators.Capital]),
        ),
        migrations.AlterField(
            model_name='identity',
            name='last_name',
            field=models.CharField(max_length=24, validators=[piradoba.validators.Capital]),
        ),
    ]
