# Generated by Django 3.2.8 on 2021-10-12 17:55

from django.db import migrations, models
import piradoba.validators


class Migration(migrations.Migration):

    dependencies = [
        ('piradoba', '0004_auto_20211012_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='birthday_date',
            field=models.DateField(default='YYYY-MM-DD', validators=[piradoba.validators.check_date]),
        ),
        migrations.AlterField(
            model_name='identity',
            name='citizen',
            field=models.CharField(max_length=3, validators=[piradoba.validators.all_upper]),
        ),
        migrations.AlterField(
            model_name='identity',
            name='expiry_date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='first_name',
            field=models.CharField(max_length=10, validators=[piradoba.validators.Capital, piradoba.validators.not_numeric]),
        ),
        migrations.AlterField(
            model_name='identity',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='identity',
            name='issue_date',
            field=models.DateField(default='YYYY-MM-DD', validators=[piradoba.validators.check_date]),
        ),
        migrations.AlterField(
            model_name='identity',
            name='last_name',
            field=models.CharField(max_length=24, validators=[piradoba.validators.Capital, piradoba.validators.not_numeric]),
        ),
    ]
