# Generated by Django 3.2.8 on 2021-10-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piradoba', '0006_alter_identity_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='personal_number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
