# Generated by Django 3.2.8 on 2021-10-13 22:16

from django.db import migrations, models
import piradoba.validators


class Migration(migrations.Migration):

    dependencies = [
        ('piradoba', '0007_alter_identity_personal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='personal_number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[piradoba.validators.personal_number_check]),
        ),
    ]
