# Generated by Django 3.2.8 on 2021-10-13 23:55

from django.db import migrations, models
import piradoba.validators


class Migration(migrations.Migration):

    dependencies = [
        ('piradoba', '0009_alter_identity_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='citizen',
            field=models.CharField(max_length=3, validators=[piradoba.validators.all_upper, piradoba.validators.alpha]),
        ),
        migrations.AlterField(
            model_name='identity',
            name='first_name',
            field=models.CharField(max_length=10, validators=[piradoba.validators.Capital, piradoba.validators.alpha]),
        ),
        migrations.AlterField(
            model_name='identity',
            name='last_name',
            field=models.CharField(max_length=24, validators=[piradoba.validators.Capital, piradoba.validators.alpha]),
        ),
    ]
