# Generated by Django 3.2.8 on 2021-10-14 10:08

from django.db import migrations, models
import piradoba.validators


class Migration(migrations.Migration):

    dependencies = [
        ('piradoba', '0010_auto_20211014_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='birth_place',
            field=models.CharField(max_length=20, validators=[piradoba.validators.Capital, piradoba.validators.alpha]),
        ),
    ]
